version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:80"
    restart: always
    networks:
      - stocknet

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend/data:/app/data
    ports:
      - "8000:8000"
    restart: always
    networks:
      - stocknet

networks:
  stocknet:
